//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppNETMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<int> login_failed_count { get; set; }
        public string login_ipaddress { get; set; }
        public string time_zone { get; set; }
        public Nullable<System.DateTime> last_accessed_date { get; set; }
        public Nullable<bool> account_lock { get; set; }
    }
}
